github: [ModyQyW, KeJunMao, Neil Lee, FliPPeDround]
custom: [
  "https://afdian.com/a/kejun",
  "https://github.com/ModyQyW/sponsors",
  "https://afdian.com/a/zguolee",
  "https://afdian.com/a/flippedround"
]
